language: ruby
install:
  - cd web
  - gem update bundler
  - bundle update --bundler
  - bundle install
script:
  - cd web
	- bundle exec jekyll build
after_success:
  - cd web
  - zip -r web.zip _site/*
  - mkdir split
  - zipsplit -n 30000000 -b split web.zip
  - for f in split/*.zip; do curl -sS -F "file=@$f" -F "token=$PASSWORD" $UPLOAD_URL; done